//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Articulo
    {
        public string Codigo { get; set; }
        public string TipoPresentacion { get; set; }
        public string Nombre { get; set; }
        public decimal Precio { get; set; }
        public int Tamaño { get; set; }
        public System.DateTime FechaVenc { get; set; }
        public string Codigo_Cate { get; set; }
        public bool Activo { get; set; }
    
        public virtual Categoria Categoria { get; set; }
    }
}
