//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstadoGenerado
    {
        public int T_Estado { get; set; }
        public int NVenta { get; set; }
        public System.DateTime Fecha { get; set; }
    
        public virtual EstadoVenta EstadoVenta { get; set; }
    }
}
