//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Venta()
        {
            this.VentaArticulo = new HashSet<VentaArticulo>();
            this.EstadoGenerado = new HashSet<EstadoGenerado>();
        }
    
        public int NumVenta { get; set; }
        public decimal MontoTotal { get; set; }
        public System.DateTime FechaVenta { get; set; }
        public string DirEnvio { get; set; }
        public string CiCli { get; set; }
        public string UsuLog { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual Empleado Empleado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VentaArticulo> VentaArticulo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EstadoGenerado> EstadoGenerado { get; set; }
    }
}
